ALTER TABLE sleeps ADD COLUMN wake_time DATETIME;
ALTER TABLE sleeps ADD COLUMN bath_time DATETIME;
ALTER TABLE sleeps ADD COLUMN sleep_time DATETIME;
ALTER TABLE sleeps ADD COLUMN report_time DATETIME;
ALTER TABLE sleeps ADD COLUMN report_min int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN picture_time DATETIME;
ALTER TABLE sleeps ADD COLUMN picture_min int DEFAULT(0);

CREATE TABLE STRETCH_GOAL(
  GOAL_ID int primary key auto_increment, 
  GOAL_NAME varchar(255) NOT NULL,
  GOAL_YEAR int NOT NULL,  
  GOAL_SEASON int NOT NULL,
  GOAL_MONTH int NOT NULL,
  GOAL_TWO_WEEK int NOT NULL,
  GOAL_WEEK int NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BASE_GOAL(
  GOAL_ID int primary key auto_increment, 
  GOAL_NAME varchar(255) NOT NULL,
  GOAL_YEAR int NOT NULL,  
  GOAL_SEASON int NOT NULL,
  GOAL_MONTH int NOT NULL,
  GOAL_TWO_WEEK int NOT NULL,
  GOAL_WEEK int NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE STEP(
  STEP_ID int primary key auto_increment, 
  STEP_NAME varchar(255) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE STEP_VALUES(
  STEP_VALUES_ID int primary key auto_increment,
  STEP_ID int NOT NULL,
  STEP_VALUE_NAME varchar(255) NOT NULL,
  STEP int NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);
