CREATE DATABASE EC;
USE EC;

GRANT SELECT, INSERT, UPDATE, DELETE ON EC.* TO 'ec'@'%';

CREATE TABLE PRODUCT(
  PRODUCT_ID int primary key auto_increment, 
  THUMB_PRIFIX varchar(255) NOT NULL,
  NAME varchar(255) NOT NULL,
  AUTHOR varchar(255) NOT NULL,
  PRICE int NOT NULL,  
  SEND int NOT NULL,
  AMOUNT int NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  PRODUCT_STATUS int DEFAULT 0 NOT NULL,
  SALE_STATUS int DEFAULT 0 NOT NULL,
  GENRE_ID int NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SALE(
  SALE_ID int primary key auto_increment,
  SALE_PRICE int NOT NULL
);

CREATE TABLE SALE_MAP(
  SALE_MAP_ID int primary key auto_increment,
  PRODUCT_ID int NOT NULL,
  SALE_ID int NOT NULL
);

CREATE TABLE GENRE(
  GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
  GENRE_NAME VARCHAR(255) NOT NULL
);

