ALTER TABLE sleeps ADD COLUMN wake_time DATETIME;
ALTER TABLE sleeps ADD COLUMN bath_time DATETIME;
ALTER TABLE sleeps ADD COLUMN sleep_time DATETIME;
ALTER TABLE sleeps ADD COLUMN report_time DATETIME;
ALTER TABLE sleeps ADD COLUMN report_min int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN picture_time DATETIME;
ALTER TABLE sleeps ADD COLUMN picture_min int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN sleep_goal_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN sleep_goal_base_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN deep_sleep_goal_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN deep_sleep_goal_base_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN sleep_step_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN sleep_step_base_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN deep_sleep_step_id int DEFAULT(0);
ALTER TABLE sleeps ADD COLUMN deep_sleep_step_base_id int DEFAULT(0);

CREATE TABLE GOAL(
  GOAL_ID int primary key auto_increment,
  GOAL_NAME varchar(255) NOT NULL,
  GOAL_YEAR int NOT NULL,  
  GOAL_SEASON int NOT NULL,
  GOAL_MONTH int NOT NULL,
  GOAL_TWOWEEK int NOT NULL,
  GOAL_WEEK int NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE STEP(
  STEP_ID int primary key auto_increment, 
  GOAL_ID int NOT NULL,
  STEP_NAME varchar(255) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE STEP_VALUE(
  STEP_VALUE_ID int primary key auto_increment,
  STEP_ID int NOT NULL,
  STEP_VALUE_NAME varchar(255) NOT NULL,
  STEP int NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);

// TODO : まだCREATEしていない。
// PROSPECT_KIND : 0 累積
//                 1 得点(上書き)
CREATE TABLE PROSPECT(
  PROSPECT_ID int primary key auto_increment,
  GOAL_ID int NOT NULL,
  BASE_GOAL_ID int NOT NULL,
  PROSPECT_NAME varchar(255) NOT NULL,
  PROSPECT_KIND int NOT NULL DEFAULT(0),
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PROSPECT_DAILY(
  PROSPECT_DAILY_ID int primary key auto_increment,
  STEP_ID int NOT NULL,
  PROSPECT_DATE DATE NOT NULL,
  PROSPECCT_VALUE int NOT NULL DEFAULT(0),
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
