openapi: "3.0.0"
info:
    title: Sleep API
    description: Sleep API.
    version: 1.0.0
servers:
    - url: http://xxx/v1
      description: version 1.
paths:
  /sleep:
    get:
      tags:
        - "sleep list."
      summary: 睡眠一覧。
      description: 睡眠一覧を取得する。
      parameters: 
        - in: query
          name: month
          required: false
          schema:
            type: string
      responses:
        "200":
          description: 睡眠一覧。
          content:
            application/json:
              schema:
                type: array
                items:
                  example:
                    - id: 853
                      date: 2026-08-01
                      wake: 160
                      bath: 8
                      bed: 98
                      sleep_in: "-"
                      sleep: 08:02:00
                      deep_sleep: 02:00:00
                      description: 電気をつけたまま寝てしまったので深い睡眠が深夜に出なかったかもです。電気を消して寝ます。3h出せると思ったのですが。まあぽちぽちで進めます。
                    - id: 854
                      date: 2026-08-02
                      wake: 194
                      bath: 153
                      bed: 243
                      sleep_in: "-"
                      sleep: 03:27:00
                      deep_sleep: 00:00:00
                      description: 暑くて起きてしまったのでそのまま起きました。続いて散歩して深い睡眠を3h出します。
        "500":
          description: エラー時。
          content:
            application/json:
              schema:
                type: array
                items:
                  example:
                    - message: サーバー内部でエラーが発生しました。 
    post:
      tags:
        - update sleep.
      summary:
        睡眠ログを更新します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: 2026-09-01
                wake:
                  type: string
                  example: 162
                bath:
                  type: string
                  example: 43
                bed:
                  type: string
                  example: 133
                sleep_in:
                  type: string
                  example: "-"              
                sleep:
                  type: string
                  example: 07:24:00
                deep_sleep:
                  type: string
                  example: 03:03:00
                description:
                  type: string
                  example: その日のメモ書きです。
      responses:
        "200":
          description: 更新成功時。
        "500":
          description: エラー時。
          content:
            application/json:
              schema:
                type: array
                items:
                  example:
                    - message: サーバー内部でエラーが発生しました。 
tags:
    - name: sleep
      description: 睡眠一覧。